import colors

def show_logo():                                                                         
  print("                                                                              ")
  print("     %@@@@@@@@@@@@@@@@@@@@@%*          .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.  ")
  print("     &@@@@@&&&&&&&&&@@@@@@@@@@@*        #&&&&&&&&&&&&&@@@@@@@&&&&&&&&&&&&&#   ")
  print("     &@@@@@/            ,&@@@@@@%                     (@@@@@#                 ")
  print("     &@@@@@/              ,@@@@@@#                    (@@@@@#                 ")
  print("     &@@@@@/               #@@@@@&                    (@@@@@#                 ")
  print("     &@@@@@/               %@@@@@#                    (@@@@@#                 ")
  print("     &@@@@@/              %@@@@@&                     (@@@@@#                 ")
  print("     &@@@@@/           (@@@@@@@(                      (@@@@@#                 ")
  print("     &@@@@@@@@@@@@@@@@@@@@@@%.                        (@@@@@#                 ")
  print("     &@@@@@@@@@@@@@@@@@@@(.                           (@@@@@#                 ")
  print("     &@@@@@/       .(@@@@@@@/                         (@@@@@#                 ")
  print("     &@@@@@/          .&@@@@@@.                       (@@@@@#                 ")
  print("     &@@@@@/            /@@@@@@*                      (@@@@@#                 ")
  print("     &@@@@@/             /@@@@@@*                     (@@@@@#                 ")
  print("     &@@@@@/              /@@@@@@,                    (@@@@@#                 ")
  print("     &@@@@@/               /@@@@@@*                   (@@@@@#                 ")
  print("     &@@@@@/                (@@@@@@*                  (@@@@@#                 ")
  print("     &@@@@@/                 (@@@@@@,                 (@@@@@#                 ")
  print("     .(###/                   .(###(.                  (###(.                 ")
  print("                                                                              ")
                                                                                

def show_info():
  show_logo()
  print(colors.off + " Version 0.5")
  print(colors.off + " ")
  print(colors.off + " Every line has to be formed by " + colors.blue + "keyword " + colors.off + "argument")
  print(colors.off + " Keywords: root_dir, add_path, add_file, add_ext, ignore_path, ignore_file, ignore_ext")
  print(colors.off + "Arguments: path/file/extension/evinronment variable with $ as first character")
  print(colors.off + "")
  print(colors.off + "Format of keywords:")
  print(colors.off + "")
  print(colors.off + "- root_dir = path|$var  (MANDATORY)")
  print(colors.off + "  -> Indicates the root directory where start to walk")
  print(colors.off + "- target_dir = path|$var (MANDATORY)")
  print(colors.off + "  -> Indicates the target directory where the file will be created")
  print(colors.off + "- target_file = filename or $var (MANDATORY)")
  print(colors.off + "  -> Indicates the target filename to be created")
  print(colors.off + "")
  print(colors.off + "- add_path path-to-add|$var path-name-inside_tar_gz")
  print(colors.off + "  -> Adds a 'path-to-add' inside_tar_gz' and its contain inside the tar.gz file as 'new-path-inside_tar_gz'")
  print(colors.off + "- add_path path-to-add|$var")
  print(colors.off + "  -> Adds 'path-to-add' and its contain inside the final tar.gz")
  print(colors.off + "")
  print(colors.off + "- add_file file-to-add ")
  print(colors.off + "- add_file file-to-add path-where-to-add ")
  print(colors.off + "-> Adds the file 'file-to-add' inside the path 'path-where-to-add'")
  print(colors.off + "")
  print(colors.off + "- add_ext path/extension")
  print(colors.off + "-> Add all the files with a certains extension inside the tar.gz. Path can be empty")
  print(colors.off + "")
  print(colors.off + "- ignore_path path")
  print(colors.off + "-> Ignore a certain path")
  print(colors.off + "")
  print(colors.off + "- ignore_file file-to-ignore|regex ")
  print(colors.off + "-> Ignores a certain file")
  print(colors.off + "")
  print(colors.off + "- ignore_ext path/extension")
  print(colors.off + "-> Ignores all the files with the indicated extesion. Path can be empty")
  print(colors.off + "")
  print(colors.off + "-> Create a file")
  print(colors.off + "-> create_file _filedesc_ _path_filename_")
  print(colors.off + "")
  print(colors.off + "-> Write a file")
  print(colors.off + "-> write_file _filedesc_ '_text_' (could be more than one line)")
  print(colors.off + "")
  print(colors.off + "-> Packs the target file- In this point begins the creation of the target file with all the instructions.")
  print(colors.off + "   The intructions that afects to pack after this point will be ignored (add_* and ignore_*)  ")
  print(colors.off + "-> write_file _filedesc_ '_text_' (could be more than one line)")